"""empty message

Revision ID: 16428883ee6b
Revises: 23f0ce9a6bfa
Create Date: 2020-08-03 16:30:44.070606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16428883ee6b'
down_revision = '23f0ce9a6bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('creation_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer', 'creation_timestamp')
    # ### end Alembic commands ###
