"""empty message

Revision ID: 23f0ce9a6bfa
Revises: 28cf9d517ed1
Create Date: 2020-07-27 16:32:48.468705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f0ce9a6bfa'
down_revision = '28cf9d517ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('cart_on_hand', sa.Integer(), nullable=True))
    op.add_column('printer', sa.Column('num_cartridges', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer', 'num_cartridges')
    op.drop_column('printer', 'cart_on_hand')
    # ### end Alembic commands ###
