"""empty message

Revision ID: 35347fb4c671
Revises: ff2c647ac60e
Create Date: 2020-08-04 19:53:02.408887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35347fb4c671'
down_revision = 'ff2c647ac60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('event_details', sa.String(length=255), nullable=True),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.Column('cartridge_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartridge_id'], ['cartridge.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_object_type'), 'event', ['object_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_object_type'), table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
