"""empty message

Revision ID: 80d5ef05dd3a
Revises: 35347fb4c671
Create Date: 2020-08-04 20:37:05.788123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d5ef05dd3a'
down_revision = '35347fb4c671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('creation_timestamp', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('updated_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'updated_timestamp')
    op.drop_column('event', 'creation_timestamp')
    # ### end Alembic commands ###
