"""empty message

Revision ID: 98385ec7692e
Revises: 16428883ee6b
Create Date: 2020-08-03 16:46:14.296365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98385ec7692e'
down_revision = '16428883ee6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_printer_creation_timestamp'), 'printer', ['creation_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_printer_creation_timestamp'), table_name='printer')
    # ### end Alembic commands ###
