"""Initial migration.

Revision ID: d94c5b8a6ec5
Revises: 
Create Date: 2020-07-22 19:05:20.892500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94c5b8a6ec5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('printer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('product_url', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printer_brand'), 'printer', ['brand'], unique=False)
    op.create_index(op.f('ix_printer_model'), 'printer', ['model'], unique=False)
    op.create_index(op.f('ix_printer_name'), 'printer', ['name'], unique=True)
    op.create_index(op.f('ix_printer_product_url'), 'printer', ['product_url'], unique=False)
    op.create_index(op.f('ix_printer_vendor'), 'printer', ['vendor'], unique=False)
    op.create_table('cartridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('product_url', sa.String(length=120), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartridge_brand'), 'cartridge', ['brand'], unique=False)
    op.create_index(op.f('ix_cartridge_color'), 'cartridge', ['color'], unique=False)
    op.create_index(op.f('ix_cartridge_model'), 'cartridge', ['model'], unique=False)
    op.create_index(op.f('ix_cartridge_product_url'), 'cartridge', ['product_url'], unique=False)
    op.create_index(op.f('ix_cartridge_vendor'), 'cartridge', ['vendor'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cartridge_vendor'), table_name='cartridge')
    op.drop_index(op.f('ix_cartridge_product_url'), table_name='cartridge')
    op.drop_index(op.f('ix_cartridge_model'), table_name='cartridge')
    op.drop_index(op.f('ix_cartridge_color'), table_name='cartridge')
    op.drop_index(op.f('ix_cartridge_brand'), table_name='cartridge')
    op.drop_table('cartridge')
    op.drop_index(op.f('ix_printer_vendor'), table_name='printer')
    op.drop_index(op.f('ix_printer_product_url'), table_name='printer')
    op.drop_index(op.f('ix_printer_name'), table_name='printer')
    op.drop_index(op.f('ix_printer_model'), table_name='printer')
    op.drop_index(op.f('ix_printer_brand'), table_name='printer')
    op.drop_table('printer')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
