"""empty message

Revision ID: ff2c647ac60e
Revises: 64b6cc1820e3
Create Date: 2020-08-04 19:26:12.099540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2c647ac60e'
down_revision = '64b6cc1820e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartridge', sa.Column('creation_timestamp', sa.DateTime(), nullable=True))
    op.add_column('cartridge', sa.Column('updated_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartridge', 'updated_timestamp')
    op.drop_column('cartridge', 'creation_timestamp')
    # ### end Alembic commands ###
